site_title = "MyArxiv"
limit_days = 7
cache_url = "https://zephyrq-z.github.io/myArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.SE"
title = "Software Engineering"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.PL"
title = "Programming Languages"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
